#!/bin/bash

# run copy bundle, bundle install, all with volume

docker compose run -e REDMINE_LANG=en redmine bin/rails db:migrate

# run the plugin's own migrations (creates the periodictasks tables)
# the dev Dockerfile overrides ENTRYPOINT, so the image's REDMINE_PLUGINS_MIGRATE
# auto-migration never runs and we have to do it explicitly here
docker compose run -e REDMINE_LANG=en redmine bundle exec rake redmine:plugins:migrate NAME=periodictask RAILS_ENV=development

# add initial data (tracker/task types, etc) to redmine database
# this script is run after redmine is up and running, so we can use the redmine container to run sql commands
docker compose run -e REDMINE_LANG=en redmine rake redmine:load_default_data

runsql() {
  echo "$1" | docker run -i --mount type=bind,source=./.volumes/sqlite/redmine.db,target=/db.db nouchka/sqlite3 /db.db
}

## set some things in database to start with plugin enabled in a project and start developing right away
### remove need to change passwd after first login
runsql "UPDATE users SET must_change_passwd=0 WHERE login='admin';"
### add a new project with periodictask module enabled
### TODO: do this only if "project1" does not exist yet in database
runsql "INSERT INTO projects (name, description, identifier, lft, rgt) VALUES ('project1', '', 'project1', 1, 2);"
runsql "INSERT INTO enabled_modules (name, project_id) VALUES ('issue_tracking', 1);"
runsql "INSERT INTO enabled_modules (name, project_id) VALUES ('periodictask', 1);"
runsql "INSERT INTO projects_trackers (project_id, tracker_id) VALUES (1, 1);"
runsql "INSERT INTO projects_trackers (project_id, tracker_id) VALUES (1, 2);"
runsql "INSERT INTO projects_trackers (project_id, tracker_id) VALUES (1, 3);"

### seed a handful of sample periodic tasks so there is data to play with right away.
### done through the app (not raw sqlite) because the running server uses WAL mode,
### and out-of-band writes to the db file race with it. tasks with a past next_run_date
### get an issue generated by the first checker run (below), giving us populated
### detail/history pages out of the box.
docker compose run --rm -e REDMINE_LANG=en redmine bin/rails runner -e development '
  tasks = [
    { subject: "Monthly report **MONTH**/**YEAR**",            tracker_id: 1, interval_number: 1, interval_units: "month",        next_run_date: 1.day.ago },
    { subject: "Weekly security scan (week **WEEKISO**)",      tracker_id: 1, interval_number: 1, interval_units: "week",         next_run_date: 2.days.ago },
    { subject: "Daily backup verification **DAY**",            tracker_id: 3, interval_number: 1, interval_units: "day",          next_run_date: 3.hours.ago },
    { subject: "Weekly dependency updates (week **WEEK**)",    tracker_id: 2, interval_number: 1, interval_units: "week",         next_run_date: 4.days.ago },
    { subject: "Quarterly business review Q**QUARTER** **YEAR**", tracker_id: 2, interval_number: 3, interval_units: "month",     next_run_date: 1.month.from_now },
    { subject: "Yearly SSL certificate renewal **YEAR**",      tracker_id: 3, interval_number: 1, interval_units: "year",         next_run_date: 2.months.from_now },
    { subject: "Biweekly team retrospective",                 tracker_id: 2, interval_number: 2, interval_units: "week",         next_run_date: 1.week.from_now },
    { subject: "Business-day on-call handover",               tracker_id: 3, interval_number: 1, interval_units: "business_day", next_run_date: 1.day.from_now },
    { subject: "Monthly invoice for **PREVIOUS_MONTHNAME**",   tracker_id: 1, interval_number: 1, interval_units: "month",        next_run_date: 5.days.from_now, due_date_number: 7, due_date_units: "day" },
    { subject: "Semiannual disaster recovery drill",          tracker_id: 3, interval_number: 6, interval_units: "month",        next_run_date: 3.months.from_now }
  ]

  tasks.each do |attrs|
    next if Periodictask.exists?(project_id: 1, subject: attrs[:subject])
    Periodictask.create!({
      project_id: 1, assigned_to_id: 1, author_id: 1, set_start_date: false,
      watcher_user_ids: [1], description: "Sample periodic task created by provision.sh"
    }.merge(attrs))
  end
'

### run the checker once so the seeded task generates at least one ticket right away
docker compose run --rm -e REDMINE_LANG=en redmine bundle exec rake redmine:check_periodictasks RAILS_ENV=development

