module RedminePeriodictask
  # Renders a "created by periodic task #n" note on the issue detail page for
  # issues that were generated by a periodic task, and a sidebar link to
  # create a periodic task from the issue being viewed.
  class Hooks < Redmine::Hook::ViewListener
    render_on :view_issues_show_description_bottom,
              partial: 'periodictask/issue_periodictask_link'

    # The sidebar partial is shared by the issue list and the issue page; the
    # link only renders on the latter (where @issue is set).
    render_on :view_issues_sidebar_issues_bottom,
              partial: 'periodictask/issue_new_periodictask_link'
  end
end
