module RedminePeriodictask
  # Renders a "created by periodic task #n" note on the issue detail page for
  # issues that were generated by a periodic task.
  class Hooks < Redmine::Hook::ViewListener
    render_on :view_issues_show_description_bottom,
              partial: 'periodictask/issue_periodictask_link'
  end
end
